---
title: "NLSY97 Breadwinning"
subtitle: "An Analysis of Mothers' Share of the Total Household Earnings"
author: "Joanna R. Pepin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

# Getting the data
This analysis uses National Longitudinal Survey of Youth 1997 (NLSY97) data downloaded from
[NLS Investigator](https://www.nlsinfo.org/investigator/pages/login.jsp).

## Data Download
To get the variables used in this analysis, after logging into the NLS Investigator and choosing the NLSY97 sample, you'll need to upload the [tagset](https://www.nlsinfo.org/content/access-data-investigator/investigator-user-guide/choose-tagsets-tab). The tagset for this project is located in the dataDir sub-folder of the repository.

To download the data, click on "Advanced Download" and click "R? Source code (includes the datafile of selected variables)." Give your download a filename and click download.

# Setup and Packages
Open and run the R script nlsy97_00_setup and packages to prepare the R environment for the project.
This file will setup the project paths and directories and attach the necessary R packages.

# Data  Import
This R code was executed in the open source edition of [RStudio](https://www.rstudio.com/products/RStudio/).  

After extracting the downloaded files, open the R file.

## 1. Set the working directory file path
You will need to your computer where to look for the downloaded data, which should be saved in dataDir, a sub-folder of the projDir.
Instead of changing the "setwd" as instructed, let's just change the relative file path using the "here" package
``` {r eval = FALSE}
new_data <- read.table(here(dataDir, 'nlsy9717.dat'), sep=' ') #The .dat should be the name of your downloaded data file.
```

## 2. Search for the missing codes and add the '#' before the lines so we can see why values are missing.

## Handle missing values

#  new_data[new_data == -1] = NA  # Refused 
#  new_data[new_data == -2] = NA  # Dont know 
#  new_data[new_data == -3] = NA  # Invalid missing 
#  new_data[new_data == -4] = NA  # Valid missing 
#  new_data[new_data == -5] = NA  # Non-interview 
  
## 3. At the bottom of the script, remove three '#' signs to create a data file called "categories" with value labels and to rename variables using Qnames instead of Reference Numbers. Then, run the entire script.

# Measures and Sample
Open the "nlsy97_measures & sample" R script to begin managing the data.
